apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - backend:
          serviceName: hello-kubernetes-custom
          servicePort: https
        path: /
  tls:
  - hosts:
    secretName: packet-secret
