apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: packet-2rjup
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["172.25.0.0/16"]
        pods: 
            cidrBlocks: ["172.26.0.0/16"]
        serviceDomain: "cluster.local"
    providerSpec:
      value:
        apiVersion: "packetprovider/v1alpha1"
        kind: "PacketClusterProviderSpec"
        projectID: 
        caKeyPair:
          cert: ""
          key: ""
