apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: packet-master-0
    labels:
      cluster.k8s.io/cluster-name: packet-2rjup
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: "packetprovider/v1alpha1"
        kind: "PacketMachineProviderSpec"
        roles:
        - Master
        OS: ubuntu_18_04
        facility:
        - ewr1
        machineType: c1.small.x86
        billingCycle: hourly
        projectID: 
        sshKeys:
    versions:
      kubelet: 1.14.3
      controlPlane: 1.14.3
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: packet-node-0
    labels:
      cluster.k8s.io/cluster-name: packet-2rjup
      set: node
  spec:
    providerSpec:
      value:
        apiVersion: "packetprovider/v1alpha1"
        kind: "PacketMachineProviderSpec"
        roles:
        - Node
        OS: ubuntu_18_04
        facility:
        - ewr1
        machineType: c1.small.x86
        billingCycle: hourly
        projectID: 
        sshKeys:
    versions:
      kubelet: 1.14.3
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: packet-lb-1
    labels:
      cluster.k8s.io/cluster-name: packet-2rjup
      set: node
  spec:
    providerSpec:
      value:
        apiVersion: "packetprovider/v1alpha1"
        kind: "PacketMachineProviderSpec"
        roles:
        - Node
        OS: ubuntu_18_04
        facility:
        - ewr1
        machineType: c1.small.x86
        billingCycle: hourly
        projectID: 
        sshKeys:
    versions:
      kubelet: 1.14.3
